# Generated by Django 4.2.3 on 2023-07-14 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 6, 52, 56, 416952, tzinfo=datetime.timezone.utc), verbose_name='modification date'),
            preserve_default=False,
        ),
    ]
