# Generated by Django 4.2.3 on 2023-07-14 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 7, 6, 36, 945035, tzinfo=datetime.timezone.utc), verbose_name='date added'),
            preserve_default=False,
        ),
    ]
